import { spawnSync } from "node:child_process";import fs from "node:fs";import path from "node:path";import { PrismaClient } from "@prisma/client";import { afterAll,beforeAll,describe,expect,it } from "vitest";import { applySeed } from "@/lib/seed";import { getArchiveMonth,getProgress,listArchiveWeeks,listFavoriteQuotes,searchHistory } from "@/lib/history-service";import { createTask,deleteTask,getDay,patchDay,patchWeek,updateTask } from "@/lib/planner-service";
const db=path.resolve("tmp/history-step7.db"),url=`file:${db.replaceAll("\\","/")}`;process.env.DATABASE_URL=url;const client=new PrismaClient({datasources:{db:{url}}});const context={systemDate:"2026-08-21",businessDate:"2026-08-21",clockWarning:false};
beforeAll(async()=>{for(const suffix of ["","-wal","-shm","-journal"])fs.rmSync(`${db}${suffix}`,{force:true});fs.mkdirSync(path.dirname(db),{recursive:true});fs.closeSync(fs.openSync(db,"a"));const migration=spawnSync(process.execPath,["node_modules/prisma/build/index.js","migrate","deploy"],{cwd:process.cwd(),env:{...process.env,DATABASE_URL:url},encoding:"utf8",windowsHide:true});if(migration.status!==0)throw new Error(migration.stderr||migration.stdout);await applySeed(client);},60000);afterAll(()=>client.$disconnect());
describe.sequential("progress, archive and search step 7",()=>{let taskId="";
it("calculates task, action and mood progress for all ranges",async()=>{await client.dailyEntry.create({data:{localDate:"2026-08-20",mood:"GOOD",selfAction:"Прогулка",selfActionCompletedAt:new Date(),closeAction:"Позвонить",closeActionCompletedAt:new Date(),morningCompletedAt:new Date()}});await client.task.createMany({data:[{localDate:"2026-08-20",title:"Готово",category:"WORK",priorityRank:1,status:"COMPLETED",sortOrder:0},{localDate:"2026-08-20",title:"План",category:"LEARNING",priorityRank:2,status:"PLANNED",sortOrder:1}]});for(const range of ["week","month","all"]){const result=await getProgress(client,context,range);expect(result.tasks).toMatchObject({plannedPriorities:2,completedPriorities:1,percentage:50,selfDays:1,otherDays:1,categoryCompleted:{WORK:1,LEARNING:0}});expect(result.tasks.moods).toEqual([{date:"2026-08-20",label:"GOOD",value:4}]);}});
it("returns archive days, weeks and favorite quotes",async()=>{await patchWeek(client,"2026-08-17",context,{goal:"Закончить отчёт"});const quote=await client.quote.findFirstOrThrow();await client.quoteUserState.upsert({where:{quoteId:quote.id},create:{quoteId:quote.id,favoriteAt:new Date()},update:{favoriteAt:new Date()}});const month=await getArchiveMonth(client,"2026-08",context);expect(month.days.find((day)=>day.date==="2026-08-20")).toMatchObject({hasRecord:true,morningCompleted:true,taskCount:2});expect((await listArchiveWeeks(client))[0]).toMatchObject({weekStart:"2026-08-17",goal:"Закончить отчёт"});expect((await listFavoriteQuotes(client)).map((item)=>item.id)).toContain(quote.id);});
it("searches Russian substrings with exact combined filters and no fuzzy match",async()=>{const task=await createTask(client,context,{localDate:"2026-08-21",title:"Обучение нейросетям",category:"LEARNING"});taskId=task.id;const opened=await getDay(client,"2026-08-21",context,()=>0);await patchDay(client,"2026-08-21",context,{version:opened.entry!.version,gratitude:"Спасибо за обучение"});expect((await searchHistory(client,context,{q:"ОБУЧ",period:"all",type:"all",category:"all"})).results).toHaveLength(2);const filtered=await searchHistory(client,context,{q:"обуч",period:"all",type:"task",category:"LEARNING"});expect(filtered.results).toMatchObject([{sourceType:"TASK",localDate:"2026-08-21",taskCategory:"LEARNING"}]);expect((await searchHistory(client,context,{q:"обучене",period:"all",type:"all",category:"all"})).results).toHaveLength(0);});
it("updates and deletes the search index transactionally and persists after reconnect",async()=>{const task=await client.task.findUniqueOrThrow({where:{id:taskId}});await updateTask(client,taskId,context,{version:task.version,title:"Практика поиска"});expect((await searchHistory(client,context,{q:"обуч",period:"all",type:"task",category:"LEARNING"})).results).toHaveLength(0);expect((await searchHistory(client,context,{q:"ПОИСК",period:"custom",from:"2026-08-21",to:"2026-08-21",type:"task",category:"LEARNING"})).results).toHaveLength(1);await deleteTask(client,taskId,context);expect(await client.searchDocument.findFirst({where:{sourceType:"TASK",sourceId:taskId}})).toBeNull();const reopened=new PrismaClient({datasources:{db:{url}}});try{expect((await listArchiveWeeks(reopened)).length).toBeGreaterThan(0);expect((await searchHistory(reopened,context,{q:"спасибо",period:"all",type:"journal",category:"all"})).results).toHaveLength(1);}finally{await reopened.$disconnect();}});
});
