import { spawnSync } from "node:child_process"; import fs from "node:fs"; import path from "node:path"; import { PrismaClient } from "@prisma/client"; import { afterAll, beforeAll, describe, expect, it } from "vitest"; import { applySeed } from "@/lib/seed"; import { getSettings, patchSettings, resetAllData, saveNotificationRule } from "@/lib/settings-service";
const db=path.resolve("tmp/settings-step8.db"),url=`file:${db.replaceAll("\\","/")}`;process.env.DATABASE_URL=url;process.env.APP_DATA_ROOT=path.resolve("tmp/settings-step8-data");const client=new PrismaClient({datasources:{db:{url}}});
beforeAll(async()=>{for(const suffix of ["","-wal","-shm","-journal"])fs.rmSync(`${db}${suffix}`,{force:true});fs.rmSync(process.env.APP_DATA_ROOT!,{recursive:true,force:true});fs.mkdirSync(path.dirname(db),{recursive:true});fs.closeSync(fs.openSync(db,"a"));const migration=spawnSync(process.execPath,["node_modules/prisma/build/index.js","migrate","deploy"],{cwd:process.cwd(),env:{...process.env,DATABASE_URL:url},encoding:"utf8",windowsHide:true});if(migration.status!==0)throw new Error(migration.stderr||migration.stdout);await applySeed(client);},60000);afterAll(()=>client.$disconnect());
describe.sequential("settings step 8",()=>{
it("starts with notifications and autostart off and protects versions",async()=>{const initial=await getSettings(client);expect(initial.settings).toMatchObject({notificationsGloballyPaused:false,autostartEnabled:false,quietHoursEnabled:false});expect(initial.rules).toEqual([]);const saved=await patchSettings(client,{version:initial.settings.version,pageTurnEnabled:false,quietHoursEnabled:true,quietStartMinutes:1320,quietEndMinutes:420});expect(saved.pageTurnEnabled).toBe(false);await expect(patchSettings(client,{version:initial.settings.version,pageTurnEnabled:true})).rejects.toMatchObject({status:409,code:"STALE_VERSION"});});
it("validates and persists notification rules",async()=>{const rule=await saveNotificationRule(client,{kind:"MORNING",enabled:true,weekdaysMask:31,timeMinutes:480,repeatAfter15:true});expect(rule).toMatchObject({enabled:true,weekdaysMask:31,timeMinutes:480,repeatAfter15:true});await expect(saveNotificationRule(client,{kind:"WATER",enabled:true,intervalMinutes:75,windowStartMinutes:540,windowEndMinutes:1260})).rejects.toMatchObject({code:"INVALID_RULE"});});
it("rolls back an artificial reset failure",async()=>{await client.task.create({data:{localDate:"2026-08-21",title:"Уникальная личная строка",category:"WORK",sortOrder:0}});await expect(resetAllData(client,"УДАЛИТЬ",true)).rejects.toThrow("RESET_TEST_FAILURE");expect(await client.task.count()).toBe(1);});
it("requires the exact phrase and resets personal data transactionally",async()=>{await expect(resetAllData(client,"удалить")).rejects.toMatchObject({code:"INVALID_CONFIRMATION"});await resetAllData(client,"УДАЛИТЬ");expect(await client.task.count()).toBe(0);expect(await client.notificationRule.count()).toBe(0);expect(await client.quote.count()).toBe(60);expect(await client.reflectionPrompt.count()).toBe(13);expect((await client.appSettings.findUniqueOrThrow({where:{id:"singleton"}})).onboardingCompletedAt).toBeNull();expect(await client.onboardingState.count()).toBe(1);});
});
