import { spawnSync } from "node:child_process";import fs from "node:fs";import path from "node:path";import { PrismaClient } from "@prisma/client";import { afterAll,beforeAll,describe,expect,it } from "vitest";import { applySeed } from "@/lib/seed";import { createWaterEntry,createWaterHabit,deleteWaterEntry,getHabit,undoLastWaterEntry,updateWaterEntry } from "@/lib/habit-service";
const db=path.resolve("tmp/water-step6.db"),url=`file:${db.replaceAll("\\","/")}`;process.env.DATABASE_URL=url;const client=new PrismaClient({datasources:{db:{url}}});const friday={systemDate:"2026-08-21",businessDate:"2026-08-21",clockWarning:false};
beforeAll(async()=>{for(const suffix of ["","-wal","-shm","-journal"])fs.rmSync(`${db}${suffix}`,{force:true});fs.mkdirSync(path.dirname(db),{recursive:true});fs.closeSync(fs.openSync(db,"a"));const migration=spawnSync(process.execPath,["node_modules/prisma/build/index.js","migrate","deploy"],{cwd:process.cwd(),env:{...process.env,DATABASE_URL:url},encoding:"utf8",windowsHide:true});if(migration.status!==0)throw new Error(migration.stderr||migration.stdout);await applySeed(client);},60000);afterAll(()=>client.$disconnect());
describe.sequential("water step 6",()=>{let id="",firstId="",secondId="";
it("creates one built-in tracker and validates the goal",async()=>{const habit=await createWaterHabit(client,friday,{goalValue:1000,weekdays:[5]});id=habit.id;expect(habit).toMatchObject({type:"WATER",status:"ACTIVE",currentRevision:{goalValue:1000,unit:"MILLILITER"}});await expect(createWaterHabit(client,friday,{goalValue:1000,weekdays:[5]})).rejects.toMatchObject({code:"WATER_ALREADY_EXISTS"});});
it("rejects invalid volumes and accepts quick and custom volumes",async()=>{for(const value of [0,-1,1.5,"текст",10001])await expect(createWaterEntry(client,id,friday,{milliliters:value})).rejects.toMatchObject({code:"INVALID_WATER_VOLUME"});firstId=(await createWaterEntry(client,id,friday,{milliliters:200})).entry.id;secondId=(await createWaterEntry(client,id,friday,{milliliters:250})).entry.id;await createWaterEntry(client,id,friday,{milliliters:300});await createWaterEntry(client,id,friday,{milliliters:451});expect((await getHabit(client,id,friday)).stats).toMatchObject({todayTotal:1201,percentage:100});expect((await client.waterEntry.findMany({where:{habitId:id},orderBy:{entryOrder:"asc"}})).map((entry)=>entry.entryOrder)).toEqual([1,2,3,4]);});
it("updates, deletes and undoes only the latest today entry",async()=>{const second=await client.waterEntry.findUniqueOrThrow({where:{id:secondId}});expect((await updateWaterEntry(client,secondId,friday,{milliliters:350,version:second.version})).stats).toMatchObject({todayTotal:1301});await deleteWaterEntry(client,firstId,friday);expect((await getHabit(client,id,friday)).stats).toMatchObject({todayTotal:1101});await undoLastWaterEntry(client,id,friday);const remaining=await client.waterEntry.findMany({where:{habitId:id},orderBy:{entryOrder:"asc"}});expect(remaining.map((entry)=>entry.milliliters)).toEqual([350,300]);expect(remaining.map((entry)=>entry.entryOrder)).toEqual([2,3]);});
it("locks the past and persists after reconnect",async()=>{const entry=await client.waterEntry.findUniqueOrThrow({where:{id:secondId}});const saturday={systemDate:"2026-08-22",businessDate:"2026-08-22",clockWarning:false};await expect(updateWaterEntry(client,entry.id,saturday,{milliliters:1,version:entry.version})).rejects.toMatchObject({code:"DATE_LOCKED"});await expect(deleteWaterEntry(client,entry.id,saturday)).rejects.toMatchObject({code:"DATE_LOCKED"});await expect(undoLastWaterEntry(client,id,saturday)).rejects.toMatchObject({code:"NO_WATER_ENTRY_TO_UNDO"});const reopened=new PrismaClient({datasources:{db:{url}}});try{expect((await getHabit(reopened,id,friday)).stats).toMatchObject({todayTotal:650,allTimeTotal:650});}finally{await reopened.$disconnect();}});
});
