"use client";

import { useMemo, useState } from "react";
import { apiRequest, InlineMessage } from "@/components/planner-ui";
import { formatRussianDate } from "@/lib/date-service";

type Status = "DRAFT" | "ACTIVE" | "PAUSED" | "ARCHIVED";
type State = "NOT_STARTED" | "EXCLUDED" | "EXTRA" | "COMPLETED" | "IN_PROGRESS" | "MISSED" | "REST";
export type PushupHabitView = { id: string; type: "PUSHUPS"; name: "Отжимания"; status: Status; startDate: string; version: number; currentRevision: { scheduleMask: number; goalValue: number } | null; today: { scheduled: boolean; excluded: boolean }; hasHistory: boolean; stats: { percentage: number | null; currentStreak: number; bestStreak: number; todaySets: Array<{ id: string; repetitions: number; setOrder: number; version: number; isExtra: boolean }>; todayTotal: number; todayBest: number; todaySetCount: number; weekTotal: number; allTimeTotal: number; calendar: Array<{ date: string; state: State; total: number }>; dailyGraph: Array<{ date: string; repetitions: number }> } };
const weekdays = ["Пн", "Вт", "Ср", "Чт", "Пт", "Сб", "Вс"];
const stateLabels: Record<State,string> = { NOT_STARTED:"Ещё не началась", EXCLUDED:"Пауза или архив", EXTRA:"Дополнительно", COMPLETED:"Цель выполнена", IN_PROGRESS:"Сегодня в процессе", MISSED:"Цель не выполнена", REST:"День отдыха" };
const maskDays = (mask: number) => weekdays.map((_, index) => index + 1).filter((day) => (mask & (1 << (day - 1))) !== 0);
function Days({ value, onChange }: { value: number[]; onChange: (days: number[]) => void }) { return <fieldset className="weekday-picker"><legend>Дни недели</legend><div>{weekdays.map((label,index) => { const day=index+1; return <label key={label}><input type="checkbox" checked={value.includes(day)} onChange={(e)=>onChange(e.target.checked?[...value,day].sort():value.filter((v)=>v!==day))}/><span>{label}</span></label>; })}</div></fieldset>; }

export function CreatePushupForm({ today, busy, onCancel, onCreate }: { today:string; busy:boolean; onCancel:()=>void; onCreate:(body:Record<string,unknown>)=>Promise<unknown> }) {
  const [goal,setGoal]=useState(30); const [days,setDays]=useState<number[]>([]); const [startDate,setStartDate]=useState(today);
  return <section className="habit-editor"><p className="eyebrow">Встроенный трекер</p><h2>Добавить отжимания</h2><label className="planner-field compact-field"><span>Цель на день, повторений</span><input type="number" min={1} max={100000} value={goal} onChange={(e)=>setGoal(Number(e.target.value))}/></label><Days value={days} onChange={setDays}/><label className="planner-field compact-field"><span>Дата начала</span><input type="date" min={today} value={startDate} onChange={(e)=>setStartDate(e.target.value)}/></label><div className="habit-actions"><button disabled={busy||!days.length||!Number.isInteger(goal)||goal<1||goal>100000} onClick={()=>void onCreate({goalValue:goal,weekdays:days,startDate})}>Добавить отжимания</button><button className="button-secondary" onClick={onCancel}>Отмена</button></div></section>;
}

type Act=(task:()=>Promise<unknown>,success:string)=>Promise<boolean>;
export function PushupDetails({ habit,busy,csrfToken,onClose,act }: { habit:PushupHabitView; busy:boolean; csrfToken:string; onClose:()=>void; act:Act }) {
  const [editing,setEditing]=useState(habit.status==="DRAFT"); const [goal,setGoal]=useState(habit.currentRevision?.goalValue??30); const [days,setDays]=useState(maskDays(habit.currentRevision?.scheduleMask??0)); const [input,setInput]=useState(""); const [inputError,setInputError]=useState(""); const [edits,setEdits]=useState<Record<string,string>>({});
  const request=(path:string,method="POST",body?:unknown)=>apiRequest<PushupHabitView>(path,csrfToken,{method,body});
  function addSet(){ const value=Number(input); if(!input.trim()||!Number.isInteger(value)||value<1||value>10000){setInputError("Введите целое число от 1 до 10000");return;} setInputError(""); void act(()=>request(`/api/v1/habits/${habit.id}/pushup-sets`,"POST",{repetitions:value}),"Подход сохранён").then((ok)=>{if(ok)setInput("");}); }
  const graph=useMemo(()=>habit.stats.dailyGraph.slice(-14),[habit.stats.dailyGraph]); const max=Math.max(goal,...graph.map((d)=>d.repetitions));
  return <section className="habit-details pushup-details"><button className="button-link" onClick={onClose}>← Ко всем привычкам</button><div className="habit-detail-heading"><div><span className={`habit-status status-${habit.status.toLowerCase()}`}>{habit.status==="ACTIVE"?"Активные":habit.status==="DRAFT"?"Черновики":habit.status==="PAUSED"?"На паузе":"Архив"}</span><h2>Отжимания</h2><p>Дневная цель — {goal} повторений</p></div>{habit.status!=="ARCHIVED"&&<button className="button-secondary" onClick={()=>setEditing(!editing)}>{editing?"Закрыть настройку":"Настроить"}</button>}</div>
  {editing&&habit.status!=="ARCHIVED"&&<div className="habit-editor inset"><InlineMessage>Изменения действуют с сегодняшнего дня. Прошлая статистика останется прежней.</InlineMessage><label className="planner-field compact-field"><span>Цель на день</span><input type="number" min={1} max={100000} value={goal} onChange={(e)=>setGoal(Number(e.target.value))}/></label><Days value={days} onChange={setDays}/><button disabled={busy||!days.length||!Number.isInteger(goal)||goal<1||goal>100000} onClick={()=>void act(()=>request(`/api/v1/habits/${habit.id}`,"PATCH",{version:habit.version,goalValue:goal,weekdays:days}),"Настройки отжиманий сохранены").then((ok)=>ok&&setEditing(false))}>Сохранить</button></div>}
  {habit.status==="ACTIVE"&&<section className="pushup-entry"><p className="eyebrow">{habit.today.scheduled?"Сегодня по плану":"Дополнительно сегодня"}</p><label className="planner-field compact-field"><span>Повторений в подходе</span><input aria-label="Повторений в новом подходе" inputMode="numeric" value={input} onChange={(e)=>{setInput(e.target.value);setInputError("");}} onKeyDown={(e)=>{if(e.key==="Enter")addSet();}}/></label>{inputError&&<InlineMessage kind="error">{inputError}</InlineMessage>}<button disabled={busy} onClick={addSet}>Сохранить подход</button></section>}
  <section className="pushup-summary"><h3>Итоги сегодня</h3><div className="stat-grid"><article><span>Всего</span><strong>{habit.stats.todayTotal}</strong><small>из {habit.currentRevision?.goalValue??0}</small></article><article><span>Лучший подход</span><strong>{habit.stats.todayBest||"—"}</strong><small>повторений</small></article><article><span>Подходов</span><strong>{habit.stats.todaySetCount}</strong><small>сегодня</small></article><article><span>За неделю</span><strong>{habit.stats.weekTotal}</strong><small>повторений</small></article></div></section>
  <section className="pushup-sets"><h3>Сегодняшние подходы</h3>{!habit.stats.todaySets.length?<p className="muted">Пока нет сохранённых подходов.</p>:<ol>{habit.stats.todaySets.map((set)=><li key={set.id}><span>Подход {set.setOrder}</span><input aria-label={`Повторения в подходе ${set.setOrder}`} value={edits[set.id]??String(set.repetitions)} onChange={(e)=>setEdits({...edits,[set.id]:e.target.value})}/><button className="button-secondary" disabled={busy||(edits[set.id]??String(set.repetitions))===String(set.repetitions)} onClick={()=>void act(()=>request(`/api/v1/pushup-sets/${set.id}`,"PATCH",{repetitions:Number(edits[set.id]),version:set.version}),"Подход исправлен")}>Сохранить</button><button className="button-link danger-link" disabled={busy} onClick={()=>window.confirm("Удалить сегодняшний подход?")&&void act(()=>request(`/api/v1/pushup-sets/${set.id}`,"DELETE"),"Подход удалён")}>Удалить</button></li>)}</ol>}</section>
  <section className="habit-statistics"><h3>Динамика</h3><div className="plank-graph" role="img" aria-label={`Отжимания по дням: ${graph.map((d)=>`${formatRussianDate(d.date)} — ${d.repetitions}`).join("; ")}`}>{graph.map((d)=><span key={d.date} title={`${formatRussianDate(d.date)}: ${d.repetitions}`}><i style={{height:`${Math.max(d.repetitions?6:1,d.repetitions/max*100)}%`}}/><small>{Number(d.date.slice(-2))}</small></span>)}</div><p>За всё время: {habit.stats.allTimeTotal} · по расписанию: {habit.stats.percentage===null?"—":`${habit.stats.percentage.toFixed(1)}%`} · дней подряд с выполненной целью: {habit.stats.currentStreak} · рекорд: {habit.stats.bestStreak} дней подряд</p><div className="habit-calendar" role="list" aria-label="Календарь отжиманий">{habit.stats.calendar.slice(-35).map((d)=><span role="listitem" aria-label={`${formatRussianDate(d.date)}: ${stateLabels[d.state]}, ${d.total}`} className={`calendar-${d.state.toLowerCase()}`} key={d.date} title={`${formatRussianDate(d.date)}: ${stateLabels[d.state]}, ${d.total}`}>{Number(d.date.slice(-2))}</span>)}</div></section>
  <section className="habit-lifecycle"><h3>Управление привычкой</h3><div className="habit-actions">{habit.status==="ACTIVE"&&<button className="button-secondary" onClick={()=>window.confirm("Поставить отжимания на паузу?")&&void act(()=>request(`/api/v1/habits/${habit.id}/pause`,"POST",{version:habit.version}),"Отжимания поставлены на паузу")}>Пауза</button>}{habit.status==="PAUSED"&&<button onClick={()=>void act(()=>request(`/api/v1/habits/${habit.id}/resume`,"POST",{version:habit.version}),"Отжимания возобновлены")}>Возобновить</button>}{habit.status!=="ARCHIVED"&&<button className="button-secondary" onClick={()=>window.confirm("Архивировать отжимания?")&&void act(()=>request(`/api/v1/habits/${habit.id}/archive`,"POST",{version:habit.version}),"Отжимания перенесены в архив")}>Архивировать</button>}{habit.status==="ARCHIVED"&&<button onClick={()=>void act(()=>request(`/api/v1/habits/${habit.id}/restore`,"POST",{version:habit.version}),"Отжимания восстановлены")}>Восстановить</button>}</div></section></section>;
}
