"use client";

import { useMemo, useState } from "react";
import { apiRequest, InlineMessage } from "@/components/planner-ui";
import { formatRussianDate } from "@/lib/date-service";

type Status = "DRAFT" | "ACTIVE" | "PAUSED" | "ARCHIVED";
type State = "NOT_STARTED" | "EXCLUDED" | "EXTRA" | "COMPLETED" | "IN_PROGRESS" | "MISSED" | "REST";
export type WaterHabitView = { id:string; type:"WATER"; name:"Вода"; status:Status; startDate:string; version:number; currentRevision:{scheduleMask:number;goalValue:number}|null; today:{scheduled:boolean;excluded:boolean}; hasHistory:boolean; stats:{percentage:number|null;completedScheduledDays:number;elapsedScheduledDays:number;currentStreak:number;bestStreak:number;todayEntries:Array<{id:string;recordedAt:string;milliliters:number;entryOrder:number;version:number;isExtra:boolean}>;todayTotal:number;allTimeTotal:number;averageOnRecordedDays:number|null;calendar:Array<{date:string;state:State;total:number}>;dailyGraph:Array<{date:string;milliliters:number}>} };
const weekdays=["Пн","Вт","Ср","Чт","Пт","Сб","Вс"];
const stateLabels:Record<State,string>={NOT_STARTED:"Ещё не началась",EXCLUDED:"Пауза или архив",EXTRA:"Дополнительно",COMPLETED:"Цель выполнена",IN_PROGRESS:"Сегодня в процессе",MISSED:"Цель не выполнена",REST:"День отдыха"};
const maskDays=(mask:number)=>weekdays.map((_,index)=>index+1).filter((day)=>(mask&(1<<(day-1)))!==0);
function Days({value,onChange}:{value:number[];onChange:(days:number[])=>void}){return <fieldset className="weekday-picker"><legend>Дни недели</legend><div>{weekdays.map((label,index)=>{const day=index+1;return <label key={label}><input type="checkbox" checked={value.includes(day)} onChange={(event)=>onChange(event.target.checked?[...value,day].sort():value.filter((value)=>value!==day))}/><span>{label}</span></label>;})}</div></fieldset>;}
function timeLabel(value:string){return new Date(value).toLocaleTimeString("ru-RU",{hour:"2-digit",minute:"2-digit"});}

export function CreateWaterForm({today,busy,onCancel,onCreate}:{today:string;busy:boolean;onCancel:()=>void;onCreate:(body:Record<string,unknown>)=>Promise<unknown>}){
  const [goal,setGoal]=useState(1500);const [days,setDays]=useState<number[]>([]);const [startDate,setStartDate]=useState(today);
  return <section className="habit-editor"><p className="eyebrow">Встроенный трекер</p><h2>Добавить воду</h2><label className="planner-field compact-field"><span>Цель на день, мл</span><input type="number" min={1} max={100000} value={goal} onChange={(event)=>setGoal(Number(event.target.value))}/></label><Days value={days} onChange={setDays}/><label className="planner-field compact-field"><span>Дата начала</span><input type="date" min={today} value={startDate} onChange={(event)=>setStartDate(event.target.value)}/></label><div className="habit-actions"><button disabled={busy||!days.length||!Number.isInteger(goal)||goal<1||goal>100000} onClick={()=>void onCreate({goalValue:goal,weekdays:days,startDate})}>Добавить воду</button><button className="button-secondary" onClick={onCancel}>Отмена</button></div></section>;
}

type Act=(task:()=>Promise<unknown>,success:string)=>Promise<boolean>;
export function WaterDetails({habit,busy,csrfToken,onClose,act}:{habit:WaterHabitView;busy:boolean;csrfToken:string;onClose:()=>void;act:Act}){
  const [editing,setEditing]=useState(habit.status==="DRAFT");const [goal,setGoal]=useState(habit.currentRevision?.goalValue??1500);const [days,setDays]=useState(maskDays(habit.currentRevision?.scheduleMask??0));const [input,setInput]=useState("");const [inputError,setInputError]=useState("");const [edits,setEdits]=useState<Record<string,string>>({});
  const request=(path:string,method="POST",body?:unknown)=>apiRequest<WaterHabitView>(path,csrfToken,{method,body});
  function add(volume:number|string){const value=Number(volume);if(String(volume).trim()===""||!Number.isInteger(value)||value<1||value>10000){setInputError("Введите целое число от 1 до 10000 мл");return;}setInputError("");void act(()=>request(`/api/v1/habits/${habit.id}/water-entries`,"POST",{milliliters:value}),`Добавлено ${value} мл`).then((ok)=>{if(ok)setInput("");});}
  const graph=useMemo(()=>habit.stats.dailyGraph.slice(-14),[habit.stats.dailyGraph]);const max=Math.max(goal,...graph.map((day)=>day.milliliters));const ratio=goal?Math.min(100,(habit.stats.todayTotal/goal)*100):0;const goalReached=habit.stats.todayTotal>=goal;
  return <section className="habit-details water-details"><button className="button-link" onClick={onClose}>← Ко всем привычкам</button><div className="habit-detail-heading"><div><span className={`habit-status status-${habit.status.toLowerCase()}`}>{habit.status==="ACTIVE"?"Активные":habit.status==="DRAFT"?"Черновики":habit.status==="PAUSED"?"На паузе":"Архив"}</span><h2>Вода</h2><p>Дневная цель — {goal} мл</p></div>{habit.status!=="ARCHIVED"&&<button className="button-secondary" onClick={()=>setEditing(!editing)}>{editing?"Закрыть настройку":"Настроить"}</button>}</div>
  {editing&&habit.status!=="ARCHIVED"&&<div className="habit-editor inset"><InlineMessage>Изменения действуют с сегодняшнего дня. Прошлая статистика останется прежней.</InlineMessage><label className="planner-field compact-field"><span>Цель на день, мл</span><input type="number" min={1} max={100000} value={goal} onChange={(event)=>setGoal(Number(event.target.value))}/></label><Days value={days} onChange={setDays}/><button disabled={busy||!days.length||!Number.isInteger(goal)||goal<1||goal>100000} onClick={()=>void act(()=>request(`/api/v1/habits/${habit.id}`,"PATCH",{version:habit.version,goalValue:goal,weekdays:days}),"Настройки воды сохранены").then((ok)=>ok&&setEditing(false))}>Сохранить</button></div>}
  {habit.status==="ACTIVE"&&<section className="water-entry"><p className="eyebrow">{habit.today.scheduled?"Сегодня по плану":"Дополнительно сегодня"}</p><h3>Добавить воду</h3><div className="water-quick-actions">{[200,250,300].map((volume)=><button key={volume} disabled={busy} onClick={()=>add(volume)}>+{volume} мл</button>)}</div><div className="water-custom"><label className="planner-field compact-field"><span>Другой объём, мл</span><input aria-label="Другой объём воды" inputMode="numeric" value={input} onChange={(event)=>{setInput(event.target.value);setInputError("");}} onKeyDown={(event)=>{if(event.key==="Enter")add(input);}}/></label><button disabled={busy} onClick={()=>add(input)}>Добавить</button></div>{inputError&&<InlineMessage kind="error">{inputError}</InlineMessage>}</section>}
  <section className={`water-summary${goalReached?" water-goal-reached":""}`}><h3>Сегодня</h3><div className="water-total"><strong>{habit.stats.todayTotal} мл</strong><span>из {goal} мл</span></div><div className="water-progress" role="progressbar" aria-label="Выполнение цели воды" aria-valuemin={0} aria-valuemax={goal} aria-valuenow={habit.stats.todayTotal}><i style={{width:`${ratio}%`}}/></div><p>{goalReached?"Цель достигнута. Дополнительная вода просто добавится к факту.":`До цели осталось ${goal-habit.stats.todayTotal} мл.`}</p></section>
  <section className="water-log"><div className="section-heading"><h3>Сегодняшние записи</h3><button className="button-secondary" disabled={busy||!habit.stats.todayEntries.length} onClick={()=>void act(()=>request(`/api/v1/habits/${habit.id}/water-entries/undo-last`),"Последняя запись отменена")}>Отменить последнюю</button></div>{!habit.stats.todayEntries.length?<p className="muted">Пока нет сохранённых записей.</p>:<ol>{habit.stats.todayEntries.map((entry)=><li key={entry.id}><span><strong>{timeLabel(entry.recordedAt)}</strong><small>Запись {entry.entryOrder}</small></span><input aria-label={`Объём записи ${entry.entryOrder}`} value={edits[entry.id]??String(entry.milliliters)} onChange={(event)=>setEdits({...edits,[entry.id]:event.target.value})}/><span>мл</span><button className="button-secondary" disabled={busy||(edits[entry.id]??String(entry.milliliters))===String(entry.milliliters)} onClick={()=>void act(()=>request(`/api/v1/water-entries/${entry.id}`,"PATCH",{milliliters:Number(edits[entry.id]),version:entry.version}),"Запись исправлена")}>Сохранить</button><button className="button-link danger-link" disabled={busy} onClick={()=>window.confirm("Удалить сегодняшнюю запись воды?")&&void act(()=>request(`/api/v1/water-entries/${entry.id}`,"DELETE"),"Запись удалена")}>Удалить</button></li>)}</ol>}</section>
  <section className="habit-statistics"><h3>Динамика</h3><div className="plank-graph" role="img" aria-label={`Вода по дням: ${graph.map((day)=>`${formatRussianDate(day.date)} — ${day.milliliters} мл`).join("; ")}`}>{graph.map((day)=><span key={day.date} title={`${formatRussianDate(day.date)}: ${day.milliliters} мл`}><i style={{height:`${Math.max(day.milliliters?6:1,day.milliliters/max*100)}%`}}/><small>{Number(day.date.slice(-2))}</small></span>)}</div><div className="stat-grid"><article><span>За всё время</span><strong>{habit.stats.allTimeTotal} мл</strong></article><article><span>Среднее</span><strong>{habit.stats.averageOnRecordedDays===null?"—":`${habit.stats.averageOnRecordedDays} мл`}</strong><small>по дням с записями</small></article><article><span>Цель достигнута</span><strong>{habit.stats.percentage===null?"—":`${habit.stats.percentage.toFixed(1)}%`}</strong><small>{habit.stats.percentage===null?"Пока нет завершённых дней":`${habit.stats.completedScheduledDays} из ${habit.stats.elapsedScheduledDays}`}</small></article></div><div className="habit-calendar" role="list" aria-label="Календарь воды">{habit.stats.calendar.slice(-35).map((day)=><span role="listitem" aria-label={`${formatRussianDate(day.date)}: ${stateLabels[day.state]}, ${day.total} мл`} className={`calendar-${day.state.toLowerCase()}`} key={day.date} title={`${formatRussianDate(day.date)}: ${stateLabels[day.state]}, ${day.total} мл`}>{Number(day.date.slice(-2))}</span>)}</div></section>
  <section className="habit-lifecycle"><h3>Управление привычкой</h3><div className="habit-actions">{habit.status==="ACTIVE"&&<button className="button-secondary" onClick={()=>window.confirm("Поставить воду на паузу?")&&void act(()=>request(`/api/v1/habits/${habit.id}/pause`,"POST",{version:habit.version}),"Трекер воды поставлен на паузу")}>Пауза</button>}{habit.status==="PAUSED"&&<button onClick={()=>void act(()=>request(`/api/v1/habits/${habit.id}/resume`,"POST",{version:habit.version}),"Трекер воды возобновлён")}>Возобновить</button>}{habit.status!=="ARCHIVED"&&<button className="button-secondary" onClick={()=>window.confirm("Архивировать воду?")&&void act(()=>request(`/api/v1/habits/${habit.id}/archive`,"POST",{version:habit.version}),"Трекер воды перенесён в архив")}>Архивировать</button>}{habit.status==="ARCHIVED"&&<button onClick={()=>void act(()=>request(`/api/v1/habits/${habit.id}/restore`,"POST",{version:habit.version}),"Трекер воды восстановлен")}>Восстановить</button>}</div></section></section>;
}
